#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class SwapChainPanel;
                ref class TextBlock;
                ref class TextBox;
                ref class ComboBox;
                ref class Button;
                ref class AppBar;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace UWPDemo
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class DirectXPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::SwapChainPanel^ swapChainPanel;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ recTarget;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtResult;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtNumberOne;
        private: ::Windows::UI::Xaml::Controls::TextBox^ txtNumberTwo;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ cboCalculation;
        private: ::Windows::UI::Xaml::Controls::Button^ btnResult;
        private: ::Windows::UI::Xaml::Controls::Button^ btnShowNotification;
        private: ::Windows::UI::Xaml::Controls::Button^ btnCreateFile;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ txtPathInstalled;
        private: ::Windows::UI::Xaml::Controls::AppBar^ bottomAppBar;
    };
}

