//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "DirectXPage.xaml.h"

void ::UWPDemo::DirectXPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///DirectXPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::UWPDemo::DirectXPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->swapChainPanel = safe_cast<::Windows::UI::Xaml::Controls::SwapChainPanel^>(__target);
        }
        break;
    case 3:
        {
            this->recTarget = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(__target);
            (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->recTarget))->PointerEntered += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Rectangle_PointerEntered);
            (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->recTarget))->PointerPressed += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Rectangle_PointerPressed);
            (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->recTarget))->PointerReleased += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Rectangle_PointerReleased);
            (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->recTarget))->PointerWheelChanged += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Rectangle_PointerWheelChanged);
            (safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(this->recTarget))->PointerMoved += ref new ::Windows::UI::Xaml::Input::PointerEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::PointerRoutedEventArgs^))&DirectXPage::Rectangle_PointerMoved);
        }
        break;
    case 4:
        {
            this->txtResult = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 5:
        {
            this->txtNumberOne = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtNumberOne))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&DirectXPage::TxtNumberOne_KeyDown);
        }
        break;
    case 6:
        {
            this->txtNumberTwo = safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBox^>(this->txtNumberTwo))->KeyDown += ref new ::Windows::UI::Xaml::Input::KeyEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::KeyRoutedEventArgs^))&DirectXPage::TxtNumberTwo_KeyDown);
        }
        break;
    case 7:
        {
            this->cboCalculation = safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ComboBox^>(this->cboCalculation))->SelectionChanged += ref new ::Windows::UI::Xaml::Controls::SelectionChangedEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::SelectionChangedEventArgs^))&DirectXPage::CboCalculation_SelectionChanged);
        }
        break;
    case 8:
        {
            this->btnResult = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->btnResult))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&DirectXPage::BtnResult_Tapped);
        }
        break;
    case 9:
        {
            this->btnShowNotification = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->btnShowNotification))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&DirectXPage::Button_Tapped);
        }
        break;
    case 10:
        {
            this->btnCreateFile = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->btnCreateFile))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&DirectXPage::BtnCreateFile_Tapped);
        }
        break;
    case 11:
        {
            this->txtPathInstalled = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
        }
        break;
    case 12:
        {
            this->bottomAppBar = safe_cast<::Windows::UI::Xaml::Controls::AppBar^>(__target);
        }
        break;
    case 13:
        {
            ::Windows::UI::Xaml::Controls::AppBarButton^ element13 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element13))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::UWPDemo::DirectXPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&DirectXPage::AppBarButton_Click);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::UWPDemo::DirectXPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


